@host = http://localhost:727
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGUiOiJVU0VSIiwidXNlcklkIjoxLCJpYXQiOjE3NDU0MjA0OTIsImV4cCI6MTc0NTQyNDA5Mn0.qpfAQ72PQXW0e7-3eK_uYKx545v4lHCuvRf-qVAzJxY
@dev_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZXZlbG9wZXIiLCJyb2xlIjoiREVWRUxPUEVSIiwidXNlcklkIjozLCJpYXQiOjE3NDU0MjAwNjIsImV4cCI6MTc0NTQyMzY2Mn0.o9sP3v_fb4_6cwaZ7V8zJPHlntk7kcQxOMAYnokhRGw
@console_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb25zb2xlIiwicm9sZSI6IlBSSVZBQ1lfUE9MSUNZIiwidXNlcklkIjoyLCJpYXQiOjE3NDU0MDUzMTgsImV4cCI6MTc0NTQwODkxOH0.0WFQhgqfN0qHW9qmW8PEKPk0m8oW4EaDHHGy2BNs_EU


### вход в аккаунт

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "user2",
  "password": "12345"
}

### запрос на подключение гугл аккаунта

POST {{host}}/api/auth/google/connect
Content-Type: application/json
Authorization: Bearer {{dev_token}}

### подключить гугл аккаунт

POST http://localhost:727/api/auth/google/connect/callback?state=90cbe11c-66c8-464d-bd87-f61f1de67cdf&code=4/0Ab_5qlksVcNA0svkIZtEIeby36hI8zbi8aFN1ExoKuW6Ln-myCP6Y-_25pfcL0XfUX7Tvw&scope=email https://www.googleapis.com/auth/userinfo.email openid&authuser=0&prompt=consent
Content-Type: application/json
Authorization: Bearer {{dev_token}}

### добавить поля в форму

POST {{host}}/api/forms/addFields
Content-Type: application/json
Authorization: Bearer {{console_token}}

[
  {"fieldName": "Email"},
  {"fieldName": "Phone Number"},
  {"fieldName": "Application ID"},
  {"fieldName": "Developer"}
]


### создать внутриигровые покупки

POST {{host}}/api/in-app-purchases/create
Content-Type: application/json
Authorization: Bearer {{dev_token}}

{
  "titles": ["Item1", "Item2"],
  "descriptions": ["Description1", "Description2"],
  "prices": [1.99, 2.99]
}

### создать приложение
POST {{host}}/api/applications
Content-Type: application/json
Authorization: Bearer {{dev_token}}

{
  "developerId": 1,
  "name": "My App",
  "type": "GAME",
  "price": 9.99,
  "description": "My App Description",
  "status": "PENDING"
}

### создать монетизированное приложение
POST {{host}}/api/monetized-applications
Content-Type: application/json
Authorization: Bearer {{dev_token}}

{
  "developerId": 1,
  "applicationId": 4,
  "currentBalance": 0,
  "revenue": 0,
  "downloadRevenue": 0,
  "adsRevenue": 0,
  "purchasesRevenue": 0
}

### привязать монетизированное приложение к покупкам
POST {{host}}/api/in-app-purchases/link-to-monetized-app/2
Content-Type: application/json
Authorization: Bearer {{dev_token}}

### создать рекламы
POST {{host}}/api/in-app-ads/bulk
Content-Type: application/json
Authorization: Bearer {{dev_token}}

[
  {
    "monetizedApplicationId": 3,
    "title": "Ad Title",
    "description": "Ad Description",
    "price": 0.5
  },
  {
    "monetizedApplicationId": 3,
    "title": "Ad Title #2",
    "description": "Ad Description #2",
    "price": 1.5
  },
  {
    "monetizedApplicationId": 3,
    "title": "Ad Title #3",
    "description": "Ad Description #3",
    "price": 2
  }
]

### создать application stats
POST {{host}}/api/application-stats
Content-Type: application/json
Authorization: Bearer {{dev_token}}

{
  "applicationId": 4,
  "downloads": 100,
  "revenue": 500
}




### создать форму для приложения
POST {{host}}/api/forms/create
Content-Type: application/json
Authorization: Bearer {{dev_token}}

### создать таблицу со статистикой приложений пользователя
POST {{host}}/api/sheets/create-revenue-sheet
Content-Type: application/json
Authorization: Bearer {{dev_token}}

###
POST {{host}}/api/sheets/1/add-sheets
Content-Type: application/json
Authorization: Bearer {{dev_token}}

###
POST {{host}}/api/user/download/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cardNumber": "1234123412341234",
  "cardHolderName": "Bob Test",
  "expiryDate": "30.03.2025",
  "cvv": "123"
}
