-- V1__initial_schema.sql


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.app_user (
                               id integer NOT NULL,
                               email character varying(255) NOT NULL,
                               password_hash character varying(255),
                               role character varying(255),
                               username character varying(255) NOT NULL,
                               CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'DEVELOPER'::character varying, 'PRIVACY_POLICY'::character varying])::text[])))
);


ALTER TABLE public.app_user OWNER TO "user";

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.application (
                                  id integer NOT NULL,
                                  description character varying(255),
                                  name character varying(255),
                                  price double precision NOT NULL,
                                  status smallint,
                                  type character varying(255),
                                  developer_id integer,
                                  CONSTRAINT application_status_check CHECK (((status >= 0) AND (status <= 2))),
                                  CONSTRAINT application_type_check CHECK (((type)::text = ANY ((ARRAY['GAME'::character varying, 'MUSIC'::character varying, 'HEALTH'::character varying, 'SOCIAL'::character varying, 'EDUCATION'::character varying, 'FINANCE'::character varying])::text[])))
);


ALTER TABLE public.application OWNER TO "user";

--
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_stats; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.application_stats (
                                        id integer NOT NULL,
                                        downloads bigint NOT NULL,
                                        rating real NOT NULL,
                                        application_id integer
);


ALTER TABLE public.application_stats OWNER TO "user";

--
-- Name: application_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.application_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: developer; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.developer (
                                id integer NOT NULL,
                                description character varying(255),
                                name character varying(255),
                                user_id integer
);


ALTER TABLE public.developer OWNER TO "user";

--
-- Name: developer_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.developer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.developer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: form_field; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.form_field (
                                 id integer NOT NULL,
                                 field_name character varying(255)
);


ALTER TABLE public.form_field OWNER TO "user";

--
-- Name: form_field_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.form_field ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: google_auth_data; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.google_auth_data (
                                       id integer NOT NULL,
                                       access_token character varying(2048) NOT NULL,
                                       expiry_date timestamp(6) with time zone,
                                       refresh_token character varying(512),
                                       scope character varying(255),
                                       token_type character varying(255),
                                       user_email character varying(255) NOT NULL,
                                       user_id integer NOT NULL
);


ALTER TABLE public.google_auth_data OWNER TO "user";

--
-- Name: google_auth_data_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.google_auth_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.google_auth_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: google_operation_result; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.google_operation_result (
                                              id bigint NOT NULL,
                                              created_at timestamp(6) without time zone,
                                              error character varying(255),
                                              operation character varying(255),
                                              result character varying(255),
                                              target_value character varying(255),
                                              user_id integer
);


ALTER TABLE public.google_operation_result OWNER TO "user";

--
-- Name: google_operation_results; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.google_operation_results (
                                               id bigint NOT NULL,
                                               user_id integer,
                                               operation character varying(50) NOT NULL,
                                               target_value text,
                                               result text,
                                               error text,
                                               created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.google_operation_results OWNER TO "user";

--
-- Name: google_operation_results_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

CREATE SEQUENCE public.google_operation_results_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;


ALTER TABLE public.google_operation_results_id_seq OWNER TO "user";

--
-- Name: google_operation_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: user
--

ALTER SEQUENCE public.google_operation_results_id_seq OWNED BY public.google_operation_results.id;


--
-- Name: in_app_add; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.in_app_add (
                                 id integer NOT NULL,
                                 description character varying(255),
                                 price double precision NOT NULL,
                                 title character varying(255),
                                 monetized_application_id integer
);


ALTER TABLE public.in_app_add OWNER TO "user";

--
-- Name: in_app_add_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.in_app_add ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.in_app_add_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: in_app_purchase; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.in_app_purchase (
                                      id integer NOT NULL,
                                      description character varying(255),
                                      price double precision NOT NULL,
                                      title character varying(255),
                                      monetized_application_id integer
);


ALTER TABLE public.in_app_purchase OWNER TO "user";

--
-- Name: in_app_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.in_app_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.in_app_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: in_app_purchase_log; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.in_app_purchase_log (
                                          id integer NOT NULL,
                                          quantity integer NOT NULL,
                                          "timestamp" timestamp(6) without time zone,
                                          in_app_purchase_id integer
);


ALTER TABLE public.in_app_purchase_log OWNER TO "user";

--
-- Name: in_app_purchase_log_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.in_app_purchase_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.in_app_purchase_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: monetized_application; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.monetized_application (
                                            id integer NOT NULL,
                                            ads_revenue double precision NOT NULL,
                                            current_balance double precision NOT NULL,
                                            download_revenue double precision NOT NULL,
                                            purchases_revenue double precision NOT NULL,
                                            revenue double precision NOT NULL,
                                            application_id integer,
                                            developer_id integer
);


ALTER TABLE public.monetized_application OWNER TO "user";

--
-- Name: monetized_application_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.monetized_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monetized_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_request; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.payment_request (
                                      id integer NOT NULL,
                                      amount double precision NOT NULL,
                                      application_id integer NOT NULL,
                                      is_card_valid boolean NOT NULL,
                                      request_time timestamp(6) without time zone
);


ALTER TABLE public.payment_request OWNER TO "user";

--
-- Name: payment_request_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.payment_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payout_log; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.payout_log (
                                 id integer NOT NULL,
                                 payout_value double precision NOT NULL,
                                 "timestamp" timestamp(6) without time zone,
                                 developer_id integer,
                                 monetized_application_id integer
);


ALTER TABLE public.payout_log OWNER TO "user";

--
-- Name: payout_log_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.payout_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payout_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_log; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.verification_log (
                                       id integer NOT NULL,
                                       ads_check_passed boolean NOT NULL,
                                       log_message character varying(255),
                                       policy_check_passed boolean NOT NULL,
                                       security_check_passed boolean NOT NULL,
                                       application_id integer
);


ALTER TABLE public.verification_log OWNER TO "user";

--
-- Name: verification_log_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.verification_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: google_operation_results id; Type: DEFAULT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.google_operation_results ALTER COLUMN id SET DEFAULT nextval('public.google_operation_results_id_seq'::regclass);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.app_user
  ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.application
  ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- Name: application_stats application_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.application_stats
  ADD CONSTRAINT application_stats_pkey PRIMARY KEY (id);


--
-- Name: developer developer_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.developer
  ADD CONSTRAINT developer_pkey PRIMARY KEY (id);


--
-- Name: form_field form_field_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.form_field
  ADD CONSTRAINT form_field_pkey PRIMARY KEY (id);


--
-- Name: google_auth_data google_auth_data_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.google_auth_data
  ADD CONSTRAINT google_auth_data_pkey PRIMARY KEY (id);


--
-- Name: google_operation_result google_operation_result_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.google_operation_result
  ADD CONSTRAINT google_operation_result_pkey PRIMARY KEY (id);


--
-- Name: google_operation_results google_operation_results_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.google_operation_results
  ADD CONSTRAINT google_operation_results_pkey PRIMARY KEY (id);


--
-- Name: in_app_add in_app_add_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_add
  ADD CONSTRAINT in_app_add_pkey PRIMARY KEY (id);


--
-- Name: in_app_purchase_log in_app_purchase_log_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_purchase_log
  ADD CONSTRAINT in_app_purchase_log_pkey PRIMARY KEY (id);


--
-- Name: in_app_purchase in_app_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_purchase
  ADD CONSTRAINT in_app_purchase_pkey PRIMARY KEY (id);


--
-- Name: monetized_application monetized_application_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.monetized_application
  ADD CONSTRAINT monetized_application_pkey PRIMARY KEY (id);


--
-- Name: payment_request payment_request_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.payment_request
  ADD CONSTRAINT payment_request_pkey PRIMARY KEY (id);


--
-- Name: payout_log payout_log_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.payout_log
  ADD CONSTRAINT payout_log_pkey PRIMARY KEY (id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.app_user
  ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: developer uk1k75gvn4hy0a5rk0ylcfbqs3y; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.developer
  ADD CONSTRAINT uk1k75gvn4hy0a5rk0ylcfbqs3y UNIQUE (user_id);


--
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.app_user
  ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- Name: google_auth_data uk45pq66e7jed9g7ejtjuelrqu4; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.google_auth_data
  ADD CONSTRAINT uk45pq66e7jed9g7ejtjuelrqu4 UNIQUE (user_id);


--
-- Name: monetized_application uke30998rsklkgr3lmcbcq7cdq2; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.monetized_application
  ADD CONSTRAINT uke30998rsklkgr3lmcbcq7cdq2 UNIQUE (application_id);


--
-- Name: application_stats ukpnj8p4dccrp6g031drls1a8u2; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.application_stats
  ADD CONSTRAINT ukpnj8p4dccrp6g031drls1a8u2 UNIQUE (application_id);


--
-- Name: verification_log verification_log_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.verification_log
  ADD CONSTRAINT verification_log_pkey PRIMARY KEY (id);


--
-- Name: idx_google_operation_results_created_at; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX idx_google_operation_results_created_at ON public.google_operation_results USING btree (created_at);


--
-- Name: idx_google_operation_results_operation; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX idx_google_operation_results_operation ON public.google_operation_results USING btree (operation);


--
-- Name: idx_google_operation_results_user_id; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX idx_google_operation_results_user_id ON public.google_operation_results USING btree (user_id);


--
-- Name: payout_log fk235j3llc7jlmjureefden4a8o; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.payout_log
  ADD CONSTRAINT fk235j3llc7jlmjureefden4a8o FOREIGN KEY (developer_id) REFERENCES public.developer(id);


--
-- Name: application_stats fk3xyuj09jf0exgbeb9q6slprga; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.application_stats
  ADD CONSTRAINT fk3xyuj09jf0exgbeb9q6slprga FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: application fk5m0c1809quegudjmrrbgod40; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.application
  ADD CONSTRAINT fk5m0c1809quegudjmrrbgod40 FOREIGN KEY (developer_id) REFERENCES public.developer(id);


--
-- Name: in_app_purchase fk9wf1lry3tu6go4ygypopdbr3u; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_purchase
  ADD CONSTRAINT fk9wf1lry3tu6go4ygypopdbr3u FOREIGN KEY (monetized_application_id) REFERENCES public.monetized_application(id);


--
-- Name: in_app_add fka82uhxgaufaytvd8mgh0ern72; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_add
  ADD CONSTRAINT fka82uhxgaufaytvd8mgh0ern72 FOREIGN KEY (monetized_application_id) REFERENCES public.monetized_application(id);


--
-- Name: verification_log fkae9quqkx93oyf6mkykf4c5pgy; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.verification_log
  ADD CONSTRAINT fkae9quqkx93oyf6mkykf4c5pgy FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: payout_log fkd4gre4y3xhut1d6o0pnmlssge; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.payout_log
  ADD CONSTRAINT fkd4gre4y3xhut1d6o0pnmlssge FOREIGN KEY (monetized_application_id) REFERENCES public.monetized_application(id);


--
-- Name: monetized_application fkefpthff25dsxrj26x3g3ifhv0; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.monetized_application
  ADD CONSTRAINT fkefpthff25dsxrj26x3g3ifhv0 FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: developer fko7byfgvq1pl297cb3lvabgd5o; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.developer
  ADD CONSTRAINT fko7byfgvq1pl297cb3lvabgd5o FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: in_app_purchase_log fkslxpf2k35f4507rbf6f3p0xge; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.in_app_purchase_log
  ADD CONSTRAINT fkslxpf2k35f4507rbf6f3p0xge FOREIGN KEY (in_app_purchase_id) REFERENCES public.in_app_purchase(id);


--
-- Name: monetized_application fkt0k808vguou2t78ogc2r1gfn8; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.monetized_application
  ADD CONSTRAINT fkt0k808vguou2t78ogc2r1gfn8 FOREIGN KEY (developer_id) REFERENCES public.developer(id);
